kind: Pod
apiVersion: v1
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  containers:
   - name: config-server
     image: navkkrnair/10-2019-config-server:2.0
     imagePullPolicy: Always
     livenessProbe:
       httpGet:
         path: /actuator/health
         port: 8888
       initialDelaySeconds: 30  
     ports:
      - containerPort: 8888
        protocol: TCP
        
---

apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  type: ClusterIP
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
  selector:
    app: config-server
---
        
          